CREATE TABLE IF NOT EXISTS Planting(
    ID_Adresse INT UNIQUE PRIMARY KEY,
    date_visit DATE NOT NULL,
    number_plantes INT UNSIGNED NOT NULL DEFAULT 1,
    CONSTRAINT fk_Planting_Adresse FOREIGN KEY (ID_Adresse) REFERENCES Adresse(ID) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS MAINTENANCE(
    ID_Adresse INT UNIQUE PRIMARY KEY,
    frequence VARCHAR(50), -- weekly,dayly,mothly,...
    week_day VARCHAR(50) NOT NULL,
    number_plantes INT UNSIGNED NOT NULL DEFAULT 1,
    CONSTRAINT fk_Planting_Adresse FOREIGN KEY (ID_Adresse) REFERENCES Adresse(ID) ON DELETE CASCADE
)