CREATE TABLE IF NOT EXISTS User (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    prenom VARCHAR(50) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,-- a modifier a 191 selon la version de mysql ou mariadb
    -- numero_telephone VARCHAR(20) NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR(255) DEFAULT 'client'
);
CREATE TABLE IF NOT EXISTS Admins (
    ID_User INT UNSIGNED PRIMARY KEY,
    niveau_acces INT UNSIGNED NOT NULL,
    date_nomination DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk__Admin__user FOREIGN KEY (ID_User) REFERENCES User (ID)
);
CREATE TABLE IF NOT EXISTS Log_Activite (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_User INT UNSIGNED NOT NULL,
    date_heure DATETIME DEFAULT CURRENT_TIMESTAMP,
    type_action VARCHAR(255) NOT NULL,
    adresse_ip VARCHAR(255) NOT NULL,
    CONSTRAINT fk__Log_Activite__user FOREIGN KEY (ID_User) REFERENCES User (ID)
);