CREATE TABLE IF NOT EXISTS Statistique_Prix (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_Plante INT UNSIGNED NOT NULL,
    prix_historique DECIMAL(10, 2) UNSIGNED NOT NULL DEFAULT 0.00,
    motif ENUM('Changement Admin', 'Promo Activée', 'Promo Expirée') DEFAULT 'Promo Activée',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Statistique_stock (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_Plante INT UNSIGNED,
    stock_historique DECIMAL(10, 2) UNSIGNED NOT NULL DEFAULT 0.00,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);